bump(x11/bochs): 3.0
- Fixes https://github.com/termux/termux-packages/issues/19677

- Drop `iodev-network-slirp-misc.cc.patch`; no longer necessary after https://github.com/bochs-emu/Bochs/pull/299

- Add `--enable-evex` to fix `error: no member named 'opmask' in 'bxInstruction_c'` (https://github.com/bochs-emu/Bochs/issues/480)