upgpkg(main/mold): update to 1.3.0
Includes:
* chore(main/mold): fix build error and cleanup build.sh
  Fix compress.cc:18:10: fatal error: 'zlib.h' file not found

Co-Authored-By: Jia Yuan Lo <jylo06g@gmail.com>