rmpkg(main/telegram-cli): upstream unmaintained and it stopped compiling
- Progress on https://github.com/termux/termux-packages/issues/23492

- Has had no updates in 10 years

- Was removed from Debian in Debian 12

- Has build failure `tgl/queries.c:2091:10: error: cast from 'void (*)(struct tgl_state *, void *, int, struct tgl_message *)' to 'void (*)(struct tgl_state *, void *, int)' converts to incompatible function type `