fix(x11/tinyemu): fix include of `libcurl`
- Progress on https://github.com/termux/termux-packages/issues/23492

- Fixes `curl/multi.h:429:23: error: expected identifier or '('`
  - it seems like `curl.h` should be included, which then includes `multi.h`, because including `multi.h` directly results in the error