fix(main/gitoxide): force-disable APK-related code in `rustls-platform-verifier`
- Fixes this error:

```
thread 'reqwest-internal-sync-runtime' (10546) panicked at /home/builder/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-platform-verifier-0.6.2/src/android.rs:94:10:
Expect rustls-platform-verifier to be initialized
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread '<unnamed>' (10545) panicked at /home/builder/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reqwest-0.13.1/src/blocking/client.rs:1522:5:
event loop thread panicked
Error: Didn't find 'application/x-git-upload-pack-advertisement' header to indicate 'smart' protocol, and 'dumb' protocol is not supported.
```

in this command:

```
gix clone https://github.com/rustls/rustls-platform-verifier.git
```