Revert "starship: update to 0.33.1"
This reverts commit f6b19109c5a06592c9e497a7b8b756fdf9b6aadb.

Compilation fails with following error:

Compiling rustls-native-certs v0.1.0
error[E0432]: unresolved import `platform`
  --> /home/builder/.cargo/registry/src/github.com-1ecc6299db9ec823/rustls-native-certs-0.1.0/src/lib.rs:22:9
   |
22 | pub use platform::load_native_certs;
   |         ^^^^^^^^ use of undeclared type or module `platform`