ci(package_updates): disable till we fix build-package.sh regression for detection for parallel builds
Although I'm late, I already managed to bomb myself with:

ERROR: Another build is already running within same environment.
ERROR: failed to build.