bump(main/sbcl): 2.6.4
- Fixes https://github.com/termux/termux-packages/issues/29605

- Reverts: https://github.com/sbcl/sbcl/commit/7c5b07f38a096ea2d0fbb89203b2c48ca671ad8b

Android's termios struct does not have `c_ispeed` or `c_ospeed`.

https://cs.android.com/android/platform/superproject/+/android-16.0.0_r4:bionic/libc/kernel/uapi/asm-generic/termios.h;l=19

This prevents:

```
../../obj/from-self/contrib/sb-posix/runme.c:1787:49: error: no member named 'c_ispeed' in 'struct termios'
```

The original purpose of the code is stated to be to fix an issue that occured when running on OpenBSD.

Preserves the test, since the test actually still passes on Android despite the code it tested having been removed,
proving that this code is unnecessary on android.