fix(main/hunspell): fix undefined symbols for arm
Previous auto-update failed for arm with:

```
ERROR: lib/libhunspell-1.7.so contains undefined symbols:
    35: 00000000     0 NOTYPE  GLOBAL DEFAULT   UND __aeabi_idiv
   123: 00000000     0 NOTYPE  GLOBAL DEFAULT   UND __aeabi_uidivmod
```

and 1.7.1 has since been absent from repo.

Issue is reported in android-ndk repo here: android/ndk#1614