Revert "e2fsprogs: update to 1.46.0"
Needs patching due to error:

/home/builder/.termux-build/e2fsprogs/src/e2fsck/rehash.c:1051:3: warning: implicit declaration of function 'qsort_r' is invalid in C99 [-Wimplicit-function-declaration]
                qsort_r(fd.harray+2, fd.num_array-2, sizeof(struct hash_entry),
                ^
        CC /home/builder/.termux-build/e2fsprogs/src/e2fsck/encrypted_files.c
        SUBST e2fsck.8
        SUBST e2fsck.conf.5
5 warnings generated.
        LD e2fsck
rehash.o:rehash.c:function e2fsck_rehash_dir: error: undefined reference to 'qsort_r'

***

This reverts commit 8b2f08e281a35ee5886bad1ced496f7848d58583.