bump(x11/qt5-qtwebengine): 5.15.18
- fix build with clang 18
- fix build with python 3.12
- fix build for 32-bit ARM (add `libopus` to dependencies explicitly,
  which prevents this error)

```
FAILED: gen/third_party/opus/celt_pitch_xcorr_arm_gnu.S
/usr/bin/python3 ../../../../src/src/3rdparty/chromium/third_party/opus/convert_rtcd_assembler.py ../../../../src/src/3rdparty/chromium/third_party/opus/src/celt/arm/arm2gnu.pl ../../../../src/src/3rdparty/chromium/third_party/opus/src/celt/arm/celt_pitch_xcorr_arm.s gen/third_party/opus/celt_pitch_xcorr_arm_gnu.S
  File "/home/builder/.termux-build/qt5-qtwebengine/build/src/core/release/../../../../src/src/3rdparty/chromium/third_party/opus/convert_rtcd_assembler.py", line 23
    print USAGE
    ^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```