silversearcher-ag: fix build with ndk-r23
Build fails due to duplicated/shared variables, like:

[...]
ld: error: duplicate symbol: out_fd
>>> defined at ignore.c
>>>            src/ignore.o:(out_fd)
>>> defined at scandir.c
>>>            src/scandir.o:(.bss+0x188)

ld: error: duplicate symbol: print_mtx
>>> defined at ignore.c
>>>            src/ignore.o:(print_mtx)
>>> defined at scandir.c
>>>            src/scandir.o:(.bss+0x8)

ld: error: duplicate symbol: root_ignores
>>> defined at ignore.c
>>>            src/ignore.o:(root_ignores)
>>> defined at scandir.c
>>>            src/scandir.o:(.bss+0x0)

ld: error: duplicate symbol: stats
>>> defined at ignore.c
>>>            src/ignore.o:(stats)
>>> defined at scandir.c
>>>            src/scandir.o:(.bss+0x190)

ld: error: duplicate symbol: alpha_skip_lookup
>>> defined at print.c
>>>            src/print.o:(alpha_skip_lookup)
>>> defined at search.c
>>>            src/search.o:(.bss+0x102B0)