serf: fix undefined version ERR_GET_FUNC
The function has been removed from openssl 3.  Annoyingly enough the
build of serf doesn't fail even with this function being undefined, it
is just reported as a warning:

buckets/ssl_buckets.c:1329:24: warning: implicit declaration of function 'ERR_GET_FUNC' is invalid in C99 [-Wimplicit-function-declaration]
                       ERR_GET_FUNC(err),
                       ^

but trying to use any program linked against libserf.so later fails.