fix({main/octave,x11/octave-x}): revbump and fix propagated $CPPFLAGS
revbump after https://github.com/termux/termux-packages/commit/db889e1 to fix propagated $CPPFLAGS

using $TERMUX_PKG_TMPDIR/_deps to only have needed libraries in the search path prevents
ld.lld: error: duplicate symbol: tzalloc in $flang_libs_dir/libc.a

putting -l:$_libgcc_name only in $LIBS instead of $LDFLAGS prevents
ld.lld: error: unable to find library -l:libclang_rt.builtins-aarch64-android.a
on-device during the pkg function https://octave.sourceforge.io/octave/function/pkg.html

prevents this error: clang++: error: no such file or directory: '/home/builder/.termux-build/_cache/android-r27c-api-24-v1/lib/clang/18/lib/linux/libclang_rt.builtins-aarch64-android.a'