mariadb: update to 10.4.11
Build for architecture i686 fails with:

/home/builder/.termux-build/mariadb/src/include/my_pthread.h:822:10: error: use of undeclared identifier 'my_atomic_add32'
  (void) my_atomic_add32_explicit(value, 1, MY_MEMORY_ORDER_RELAXED);
         ^