bump(x11/qt6-qtbase): 6.9.0
Disable the change from the following commit.
https://code.qt.io/cgit/qt/qtbase.git/commit/src/corelib/io/qstorageinfo_linux.cpp?h=v6.9.0&id=0db5b424cdaede8724886e8a1eda1380382d9aaf

It fixes the following compiler error.
qstorageinfo_linux.cpp:40:10: fatal error: 'private/qjnihelpers_p.h' file not found