enhance(scripts/build/termux_step_massage): check for non-position-independent executables
- a [`check-pie.sh`](https://github.com/termux/termux-packages/blob/5ed8471923a57fab306148c2cdef88df49550b68/scripts/bin/check-pie.sh) exists, but it is an isolated tool, and is not connected to CI.

https://github.com/termux/termux-packages/blob/5ed8471923a57fab306148c2cdef88df49550b68/scripts/bin/check-pie.sh#L1-L12

- https://github.com/termux/termux-packages/issues/23598 could have been prevented, in retrospect, if a long time ago when `simulide` was last built, `check-pie.sh` had been connected to CI.

- This is an attempt to try to copy and paste the contents of `check-pie.sh` into the symbol checks block of `termux_step_massage.sh`, in order to possbly enable it

- effects:

  - before https://github.com/termux/termux-packages/commit/e462a5dd1c32bcd5682783c141e04573209a838a:

```
INFO: Running symbol checks on 1 files with nproc=32
INFO: Done ... 0s
INFO: Found non-position-independent executables
INFO: Showing result
ERROR: ./bin/simulide is a non-position-independent executable
INFO: Done ... 0s
ERROR: Refer above
```

  - after https://github.com/termux/termux-packages/commit/e462a5dd1c32bcd5682783c141e04573209a838a:

```
INFO: Running symbol checks on 1 files with nproc=32
INFO: Done ... 1s
termux - build of 'simulide' done
```

- **has been tested minimally in both `$TERMUX_ON_DEVICE_BUILD=true` mode and `$TERMUX_ON_DEVICE_BUILD=false` mode, but has not been heavily tested with all packages yet**. Because `check-pie.sh` has never been connected to CI, there is a chance it might produce **false positives** with some unknown packages, in which case a `TERMUX_PKG_NO_PIE_FILES` variable would be necessary to implement, for those packages. This PR serves to float the idea to check whether this is considered worthwhile enough to try.