bump(main/bear): 4.1.0
- Fixes https://github.com/termux/termux-packages/issues/29133

- rebase `implementation.rs.patch`

- `build.rs.patch` is no longer necessary

- disable `posix_spawn` because `libandroid-spawn` is no longer interoperable with `bear`, because of `error[E0425]: cannot find function 'posix_spawnattr_init' in crate 'libc'`

- Install using `scripts/install.sh` instead of manually