ghostscript: Update to 9.21 and patch to make it build. (#867)
Package builds but doesn't work on device, running gs gives error:
"GPL Ghostscript 9.21: /home/builder/.termux-build/ghostscript/src/psi/interp.c(303): Fatal error -20 in gs_interp_init!"