fix(main/udocker): support 32-bit x86
Fixes this error in `udocker pull debian` on 32-bit x86 Android:

```
  File "/data/data/com.termux/files/usr/lib/python3.13/site-packages/udocker/helper/hostinfo.py", line 30, in arch
    return arch[0] if arch[0] else ""
                      ~~~~^^^
IndexError: list index out of range
```

all devices that 32-bit x86 Android 7 and newer support print "`i686`" when the command `uname -m` is used.