Revert "bochs: update to 2.6.10"
Version 2.6.10 fails to build with following error:

  cpu/libcpu.a(init.o):init.cc:function BX_CPU_C::initialize(): error: undefined reference to 'create_corei7_icelake_u_cpuid(BX_CPU_C*)'

Delaying update to the next bochs release.

This reverts commit dc65484708761cea0bd830a5c4f08ba0e039be81.