chore(x11/pyqt5): Add version requirements for runtime and build time dependencies
This prevents running pyqt5 with older version of pyqt5-sip and fixes
the following runtime error.

RuntimeError: the sip module implements API v12.0 to v12.12 but the PyQt5.QtCore module requires API v12.13