fix(main/bash): build target to clang instead of gcc
Workaround for:
In file included from mkbuiltins.c:46:
../bashansi.h:44:23: error: ‘bool’ cannot be defined via ‘typedef’
   44 | typedef unsigned char bool;
      |                       ^~~~
../bashansi.h:44:23: note: ‘bool’ is a keyword with ‘-std=c23’ onwards
../bashansi.h:44:1: warning: useless type name in empty declaration
   44 | typedef unsigned char bool;
      | ^~~~~~~