fix(scripts/update-packages): Check for github based packages
- Do not assume package source only from `TERMUX_PKG_SRCURL`.
  Check `TERMUX_PKG_UPDATE_METHOD` too.

Problem?
- github based packages that uses repology method for update gets wrong
  version cached by `_fetch_and_cache_tags`. Thus, leading to errors
  like:
  ```
  INFO: Updating libicu [Current version: 77.1]
  ERROR: ::warning::libicu: dpkg: warning: version 'release-78.1' has bad syntax: version number does not start with digit
  ```

Signed-off-by: Aditya Alok <alok@termux.dev>