updpkg(root/frida): update to 16.0.2
With this update frida is pretty much fully functional again.

Fixes termux/termux-packages#11415
Fixes termux/termux-packages#11113
Fixes termux/termux-packages#12632

frida-discover, which was reported broken in
termux/termux-packages#10170 still does not seem to work (though error
is different than in linked issue):

$ frida-discover -p 9102
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/frida-discover", line 7, in <module>
    import frida_tools.discover
ModuleNotFoundError: No module named 'frida_tools.discover'