Revert "starship: update to 0.42.0"
error: attributes are not yet allowed on `if` expressions
  --> /home/builder/.cargo/registry/src/github.com-1ecc6299db9ec823/sysinfo-0.14.5/src/utils.rs:27:5
   |
27 |     #[allow(clippy::identity_conversion)]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error