bump(main/yosys): 0.47
Use git repository in source URL to get abc and cxxopts git submodules
which are absent in git generated source tarball.

This commit fixes the following compiler error.
kernel/driver.cc:22:10: fatal error: 'libs/cxxopts/include/cxxopts.hpp' file not found