bump(x11/praat): 6.4.50
Add -DWORDS_BIGENDIAN=0 compiler flag which is required for the following commit.
https://github.com/praat/praat.github.io/commit/a4425d2b2f01d5fbd05773702f31572d9bb98c61

Otherwise, this compiler error is shown

praat.cpp:2395:4: error: WORDS_BIGENDIAN should be #defined
 2395 |                 #error WORDS_BIGENDIAN should be #defined
      |                  ^