fix(main/libnfc): fix building with `./build-all.sh`
Fixes the following error which appears during running `./build-all.sh`.
```
/home/builder/.termux-build/libnfc/src/examples/pn53x-tamashell.c:48:12: fatal error: 'readline/readline.h' file not found
   48 | #  include <readline/readline.h>
      |            ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Since `libnfc.so` has only `libc.so` in `NEEDED` section I put `readline` to build dependency section.

Related to #21130.