fix(scripts/setup-offline-bundle.sh): don't install pip
As of now this cannot be done for offline bundle.

 ERROR: /data/data/com.termux/files/usr/bin/python3.11 does not exist