fix(main/libunbound): add missing `python` build dependency in case package needs to be built without `pyunbound.subpackage.sh`
```
[termux_setup_python_pip]: Applying python-crossenv-PYTHONPATH.patch
ERROR: /data/data/com.termux/files/usr/bin/python3.11 does not exist
```