fix(main/monero): fix build of version 0.18.4.5 for x86 targets
- Disabling stack trace for x86 avoids these two errors when building for Android-x86:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBUNWIND_LIBRARIES (ADVANCED)
```

```
src/common/stack_trace.cpp:155:19: error: invalid operands to binary expression ('Writer' and '__iom_t6')
```