bump(main/xmlsec): 1.3.12
Add configure option to disable strict handling of warnings as error.
list_unit_tests.c:826:2: error: no newline at end of file [-Werror,-Wnewline-eof]

Also, remove the patch file which was added for same error as above.