fix(main/libjxl-progs): add missing dep openexr
The executables `cjxl` and `djxl` fail without the package `openexr` installed.
Error: `CANNOT LINK EXECUTABLE "cjxl": library "libOpenEXR-3_2.so" not found: needed by main executable`