Revert "newsboat: update to 2.20"
error[E0432]: unresolved imports `libc::regcomp`, `libc::regerror`, `libc::regex_t`, `libc::regexec`, `libc::regfree`, `libc::regmatch_t`