fix(packages/cmake): fix build-time error
`CURL_NETRC_OPTION` is declared as `enum` type and clang can not cast `long` values implicitly. The patch explicitly casts these values.
```console
[59/494] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmCurl.cxx.o
FAILED: Source/CMakeFiles/CMakeLib.dir/cmCurl.cxx.o
/home/builder/.termux-build/_cache/android-r27c-api-24-v1/bin/clang++ --target=aarch64-none-linux-android --gcc-toolchain=/home/builder/.termux-build/_cache/android-r27c-api-24-v1 --sysroot=/home/builder/.termux-build/_cache/android-r27c-api-24-v1/sysroot  -I/home/builder/.termux-build/cmake/build/Utilities -I/home/builder/.termux-build/cmake/build/Source -I/home/builder/.termux-build/cmake/src/Source -I/home/builder/.termux-build/cmake/src/Source/LexerParser -isystem /home/builder/.termux-build/cmake/src/Utilities/std -isystem /home/builder/.termux-build/cmake/src/Utilities -fstack-protector-strong -Oz --target=aarch64-linux-android24  -isystem/data/data/com.codewiz.inferra/files/usr/include/c++/v1 -isystem/data/data/com.codewiz.inferra/files/usr/include -O3 -DNDEBUG -std=c++17 -fPIC -Wno-deprecated-declarations -MD -MT Source/CMakeFiles/CMakeLib.dir/cmCurl.cxx.o -MF Source/CMakeFiles/CMakeLib.dir/cmCurl.cxx.o.d -o Source/CMakeFiles/CMakeLib.dir/cmCurl.cxx.o -c /home/builder/.termux-build/cmake/src/Source/cmCurl.cxx
/home/builder/.termux-build/cmake/src/Source/cmCurl.cxx:178:26: error: assigning to 'CURL_NETRC_OPTION' from incompatible type 'long'
  178 |       curl_netrc_level = CURL_NETRC_OPTIONAL;
      |                          ^~~~~~~~~~~~~~~~~~~
/data/data/com.codewiz.inferra/files/usr/include/curl/curl.h:2355:29: note: expanded from macro 'CURL_NETRC_OPTIONAL'
 2355 | #define CURL_NETRC_OPTIONAL 1L /* A user:password in the URL will be preferred
      |                             ^~
/home/builder/.termux-build/cmake/src/Source/cmCurl.cxx:180:26: error: assigning to 'CURL_NETRC_OPTION' from incompatible type 'long'
  180 |       curl_netrc_level = CURL_NETRC_REQUIRED;
      |                          ^~~~~~~~~~~~~~~~~~~
/data/data/com.codewiz.inferra/files/usr/include/curl/curl.h:2357:29: note: expanded from macro 'CURL_NETRC_REQUIRED'
 2357 | #define CURL_NETRC_REQUIRED 2L /* A user:password in the URL will be ignored.
      |                             ^~
/home/builder/.termux-build/cmake/src/Source/cmCurl.cxx:182:26: error: assigning to 'CURL_NETRC_OPTION' from incompatible type 'long'
  182 |       curl_netrc_level = CURL_NETRC_IGNORED;
      |                          ^~~~~~~~~~~~~~~~~~
/data/data/com.codewiz.inferra/files/usr/include/curl/curl.h:2353:29: note: expanded from macro 'CURL_NETRC_IGNORED'
 2353 | #define CURL_NETRC_IGNORED  0L /* The .netrc will never be read.
      |                             ^~
3 errors generated.
```

[no ci]