fix(x11/qt5-qtbase): mark as depending on `libglvnd-dev`
- Similar to what we decided to do in https://github.com/termux/termux-packages/pull/30369

- Prevents errors like this when building software that uses the `qopengl.h` header:

```
/data/data/com.termux/files/usr/include/qt6/QtGui/qopengl.h:115:13: fatal error: 'GL/gl.h' file not found
  115 | #   include <GL/gl.h>
      |             ^~~~~~~~~
```

- While compiled programs do not depend on headers at runtime, the precedent with the `xorgproto` decision now implies that all packages that contain usable development headers that import other development headers should be marked as depending at runtime on the packages that provide those other development headers, to ensure that users building software manually on-device will always get all necessary headers when they use commands like `pkg install qt6-qtbase`.