bump(main/yosys): 0.67
Remove the makefile patch because yosys now uses cmake instead of make.

Disable building for 32 bit architectures due to following error.
SVIntHelpers.h:287:32: error: __int128 is not supported on this target