fix(x11/orca): Add missing runtime dependencies
orca shows the following errors without these packages.

* xorg-xkbcomp
  FileNotFoundError: [Errno 2] No such file or directory: 'xkbcomp'

* gsettings-desktop-schemas
  GLib-GIO-ERROR: Settings schema 'org.gnome.desktop.a11y.applications' is not installed